Kubernetes blog post
StatusNeo/Hacktoberfest_2020 pull request #22
Opened 2020-10-04 07:37 UTC by whiskerwind

Adding Kubernetes blog post

2020-10-04 07:44 UTC, NishkarshRaj commented on blogs/Kubernetes.md
> +<caption>kubenetes logo</caption>
```suggestion
<p align="center">
<img src="https://octoperf.com/img/blog/kraken-kubernetes-ingress-nginx-frontend/kubernetes.png" width="400">
</p>
```

2020-10-04 07:44 UTC, NishkarshRaj requested changes
@whiskerwind make following changes:

1. Center align the image attached - already suggested in comments
2. Add blog link in this PR

2020-10-04 08:46 UTC, whiskerwind commented
thanks for the feedback 👍  I have updated the PR

2020-10-05 09:51 UTC, NishkarshRaj approved these changes
Thanks @whiskerwind for your contribution 👍

2020-10-05 09:51 UTC, merged